[package]
name = "ohm"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {version = "1.14.0", features = ["rt-multi-thread"]}
tonic = "0.6"
structopt = "0.3.25"
prost = "0.9"

[build-dependencies]
tonic-build = "0.6"
